name: SSH Ubuntu

on: workflow_dispatch

jobs:
  ssh-session:
    runs-on: ubuntu-latest
    steps:
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
