name: SSH over Ngrok

on: workflow_dispatch

jobs:
  ssh-info:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server jq
          echo "root:toor123" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install -y ngrok

      - name: Start ngrok tunnel and show info
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok config add-authtoken $NGROK_AUTH_TOKEN
          nohup ngrok tcp 22 --region eu > /dev/null &
          sleep 5
          INFO=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          # INFO example: tcp://0.tcp.eu.ngrok.io:12345
          IP=$(echo $INFO | cut -d':' -f2 | sed 's#//#//#g' | cut -d'/' -f3)
          PORT=$(echo $INFO | cut -d':' -f3)
          USER=root
          PASS=toor123
          echo "=========================="
          echo "SSH connection info:"
          echo "$IP:$PORT@$USER:$PASS"
          echo "=========================="
